# Generated by Django 3.0 on 2019-12-10 22:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=140)),
                ('email', models.EmailField(max_length=254)),
                ('cartao', models.IntegerField()),
                ('Pagamento', models.CharField(choices=[('AV', 'Pagamento á vista'), ('P2', 'Parcelado em 2x'), ('P3', 'Parcelado em 3x')], max_length=2)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='postagem',
            name='email',
        ),
        migrations.RemoveField(
            model_name='postagem',
            name='texto_blog',
        ),
        migrations.AlterField(
            model_name='postagem',
            name='tema',
            field=models.CharField(choices=[('ROM', 'Romance'), ('TE', 'Tecnologia'), ('NO', 'Novidades')], max_length=3),
        ),
    ]
